name: Post Twitter Photo

on:
  schedule:
    - cron: "0 */2 * * *"

  workflow_dispatch:

jobs:
  post_twitter_photo:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Tweet Summary
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_tweet_summary.py

      - name: Run script
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python bot.py